In [ ]:
#럭키 스트레이트
score = input()
score_list = list(score)
n = len(score_list)

left_score = 0
right_score = 0

for i in range(0,n//2):
  left_score += int(score_list[i])
  
for i in range(n//2,n):
  right_score += int(score_list[i])
  

if left_score == right_score:
  print('LUCKY')
else:
  print('READY')

123402
LUCKY


In [ ]:
#문자열 재정렬
i_string = input()
s_string = sorted(i_string)

n = 0
o_string = ''
for char in s_string:
  if char.isdigit():
    n += int(char)
  else:
    o_string += char

print(o_string + '{}'.format(n))


DKJAAN343NLNLA45
AAADJKLLNNN19


In [ ]:
#@title
#문자열 압축
# i_string = input()
i_string = 'aabaabcccccccc'
print(i_string)
# l_string = list(i_string)

comp_list = []

def str_block(start_idx, len_block, i_string):
  return i_string[start_idx:start_idx+len_block]

for i in range(1, len(i_string)): #len_block = i
  start_idx = 0
  next_idx = start_idx + i
  block_cnt = 1
  
  comp = ''
  while start_idx < len(i_string):
    # print(str_block(start_idx, i, i_string), str_block(next_idx, i, i_string))
    
    if str_block(start_idx, i, i_string) == str_block(next_idx, i, i_string):
      block_cnt += 1
      start_idx = next_idx
      next_idx += i
      # print('A')
    else:
      if block_cnt>1:
        comp += str(block_cnt) + str_block(start_idx, i, i_string)
        block_cnt = 1
        start_idx = next_idx
        next_idx = start_idx+i
        # print('B')
      else:
        comp += i_string[start_idx]
        start_idx += 1
        next_idx = start_idx+i
        # print('C')
  print('comp',i, comp)
  comp_list.append(len(comp))
print(min(comp_list))




aabaabcccccccc
comp 1 2ab2ab8c
comp 2 aabaab4cc
comp 3 2aab2ccccc
comp 4 aabaab2cccc
comp 5 aabaabcccccccc
comp 6 aabaabcccccccc
comp 7 aabaabcccccccc
comp 8 aabaabcccccccc
comp 9 aabaabcccccccc
comp 10 aabaabcccccccc
comp 11 aabaabcccccccc
comp 12 aabaabcccccccc
comp 13 aabaabcccccccc
8


In [ ]:
#문자열 압축

def solution(s):
  answer = 0

  # 비교할 블록 정의
  def str_block(start_idx, len_block, s):
    return s[start_idx:start_idx+len_block]

  # 압축 문자열 비교 리스트
  comp_list = []
  for i in range(1, len(s)): #len_block = i
    # 블록 인덱싱 초기화
    start_idx = 0
    next_idx = start_idx + i
    block_cnt = 1

    # 압축 문자열 초기화    
    comp = ''
    while start_idx < len(s):    
      # 블록 동일 
      if str_block(start_idx, i, s) == str_block(next_idx, i, s):
        block_cnt += 1
        start_idx = next_idx
        next_idx += i

      else:
        # 이전 블록이 압축된 경우
        if block_cnt>1:
          comp += str(block_cnt) + str_block(start_idx, i, s)
          block_cnt = 1

          start_idx = next_idx##
          next_idx = start_idx+i

        # 이전 블록이 압축되지 않은 경우 
        else:
          comp += s[start_idx]
          start_idx += 1##
          next_idx = start_idx+i

    comp_list.append(len(comp))

  answer = min(comp_list)
  return answer


s = 'xababcdcdababcdcd'
result = solution(s)
print(result)

10


In [ ]:
#@title
import numpy as np
#자물쇠와 열쇠

# lock = [[0]*n for _ in range(n)]
# key = [[0]*m for _ in range(m)]

# key = np.array( [[0,0,1], [0,0,0], [0,0,0]])
# lock = np.array( [[1,1,1,1,0], [1,1,1,1,1], [1,1,1,1,1], [1,1,1,1,1], [1,1,1,1,1]])

key = np.array( [[1,1], [0,0]])
lock = np.array( [[1,1,1], [1,1,1], [1,1,0]])

m = 2
n = 3
print(key)
print(lock)

def rotate_key(key):
  r_key = np.array([[0] * m for _ in range(m)])
  for i in range(m):
    for j in range(m):
      r_key[i][j]= key[m-1-j][i]
  return r_key

r_key = rotate_key(key)
print(r_key)


def pad_lock(lock):
  p = n+2*(m-1)
  p_lock = np.array([[0] * (p) for _ in range(p)])
  for i in range(n):
    for j in range(n):
      p_lock[i+m-1][j+m-1] = lock[i][j]
  return p_lock

p_lock = pad_lock(lock)
print(p_lock)

def match(r_key,p_lock):

  for i in range(m+n-1):
    for j in range(m+n-1):
      #초기화
      val = True
      val_lock = p_lock.copy()
      #자물쇠랑 키 더하기
      for a in range(m):
        for b in range(m):
          val_lock[i+a][j+b] = val_lock[i+a][j+b] + r_key[a][b]
      print(val_lock)
      #자물쇠 1 체크
      for x in range(n):
        for y in range(n):
          if val_lock[m-1+x][m-1+y] != 1:
            val = False
            break#y
        if val==False:
          break#x >> 다른 위치로 더하기
            
      if val==True: #i,j 찾음
        print(i,j)
        return True
      #j
    #i
  return False
      

print(match(r_key,p_lock))


[[1 1]
 [0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 0]]
[[0 1]
 [0 1]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 1 0 0 0]
 [0 2 1 1 0]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 1 0 0]
 [0 1 2 1 0]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 1 0]
 [0 1 1 2 0]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 1]
 [0 1 1 1 1]
 [0 1 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 2 1 1 0]
 [0 2 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 2 1 0]
 [0 1 2 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 2 0]
 [0 1 1 2 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 1 1 1]
 [0 1 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 2 1 1 0]
 [0 2 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 2 1 0]
 [0 1 2 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 2 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [0 1 1 0 1]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 2 1 0 0]
 [0 1 0 0 0]]
[[0 0 0 0 0]
 [0 1

In [ ]:
#자물쇠와 열쇠
import numpy as np
def solution(key, lock):
    m =len(key)
    n =len(lock)
    answer = False

    def rotate_key(key):
        r_key = np.array([[0] * m for _ in range(m)])
        for i in range(m):
            for j in range(m):
                r_key[i][j]= key[m-1-j][i]
        return r_key
    # r_key = rotate_key(key)

    def pad_lock(lock):
        p = n+2*(m-1)
        p_lock = np.array([[0] * (p) for _ in range(p)])
        for i in range(n):
            for j in range(n):
                p_lock[i+m-1][j+m-1] = lock[i][j]
        return p_lock
    # p_lock = pad_lock(lock)

    def match_key(r_key,p_lock):
        for i in range(m+n-1):
            for j in range(m+n-1):
                #초기화
                val = True
                val_lock = p_lock.copy()
                #자물쇠랑 키 더하기
                for a in range(m):
                    for b in range(m):
                        val_lock[i+a][j+b] = val_lock[i+a][j+b] + r_key[a][b]
                # print(val_lock)
            #자물쇠 1 체크
                for x in range(n):
                    for y in range(n):
                        if val_lock[m-1+x][m-1+y] != 1:
                            val = False
                            break#y
                    if val==False:
                        break#x >> 다른 위치로 더하기
                    
                if val==True: #i,j 찾음
                    return True
            #j
        #i
        return False

    for _ in range(4):
        r_key = rotate_key(key)
        p_lock = pad_lock(lock)
        # print(r_key)
        # print(p_lock)
        if match_key(r_key, p_lock)==True:
            answer = True
            break
        else:
            key = r_key
    return answer
      

key = np.array([[1,1], [0,0]])
lock = np.array([[1,1,1], [1,1,1], [1,1,0]])
solution(key,lock)

True

In [ ]:
##뱀
import numpy as np
# n = int(input())
# # k = int(input())
# board = np.array([[0] * n for _ in range(n)])
# for _ in range(k):
#     a, b = map(int, input().split())
#     board[a][b] = 1
# time_turn = []
# l = int(input())
# for _ in range(l):
#     t, c = input().split()
#     time_turn.append(int(t),c)


####board:1-base
n = 6
k = 3
board = np.array([[0] * (n) for _ in range(n)])
apple = [[3,4], [2,5], [5,3]]
l = 3
time_turn = [[3,'D'], [15,'L'], [17,'D']]

#사과
for i in range(k):
    x = apple[i][0]
    y = apple[i][1]
    print(x,y)
    board[x-1][y-1] = 1
print(board)

#방향 회전
dx = [0, 1, 0, -1]
dy = [1, 0, -1, 0]


def turn(direction,c):
    if c == 'L':
        direction = (direction -1) % 4
    else:
        direction = (direction +1) % 4
    return direction


#뱀 초기값
x,y = 0, 0
board[x][y] = 2
direction = 0
time = 0
baam = [(x,y)]
print(board,baam,time)

#시뮬레이션 시작//break: 부딪쳤을때, return:time
while True:
    # 머리 이동할 때
    nx = x + dx[direction]
    ny = y + dy[direction]

    #머리가 벽이나 몸통에 부딪치지 않는가
    if 0<=nx<n and 0<=ny<n and board[nx][ny]!=2:
        #사과가 없는가
        if board[nx][ny]==0:
            #머리업뎃
            board[nx][ny]=2
            baam.append((nx,ny))
            #꼬리제거
            px,py = baam.pop(0)
            board[px][py]=0

        #있는가
        if board[nx][ny]==1:
            #머리업뎃, 꼬리 그대로
            board[nx][ny]=2
            baam.append((nx,ny))
    #부딪쳤는가
    else:
        time +=1
        print(board,baam,time)
        break
    #이후 task
    x, y = nx, ny
    time+=1 #time은 되도록 마지막에 올리고 break있는 곳에 추가하는 방식으로

    print(board,baam,time)
    #회전 시간일때 회전하기
    t_idx = 0
    if time == time_turn[t_idx][0] and t_idx<l:
        direction = turn(direction,time_turn[t_idx][1])
        t_idx += 1
print(time)
# return time



3 4
2 5
5 3
[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]]
[[2 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(0, 0)] 0
[[0 2 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(0, 1)] 1
[[0 0 2 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(0, 2)] 2
[[0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(0, 3)] 3
[[0 0 0 0 0 0]
 [0 0 0 2 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(1, 3)] 4
[[0 0 0 0 0 0]
 [0 0 0 2 1 0]
 [0 0 0 2 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(1, 3), (2, 3)] 5
[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 2 0 0]
 [0 0 0 2 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]] [(2, 3), (3, 3)] 6
[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 2 0 0]
 [0 0 1 2 0 0]
 [0 0 0 0 0 0]] [(3, 3), (4, 3)] 7
[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 

In [ ]:
##기둥과 보 설치

##def check(): return T/F
    #case1.기둥 x y 0 1 , b[x,y]=0
    #바닥 위/보의 끝/기둥 위
    y=0 or (b[x-1,y]==1 or b[x,y]==1) or b[x,y-1]==0

    #case2.보 x y 1 1, b[x,y]=1
    #기둥 위/양쪽 보
    b[x,y-1]==0 or b[x+1,y-1]==0 or (b[x-1,y]==1 and b[x+1,y]==1)

##def delete(): return T/F
#기둥 삭제 #x,y >check([x,y+1]:case1,2 , [x-1,y+1]:case2)
#보 삭제 #x,y >check([x-1,y]:case2 , [x,y]:case1, [x+1,y]:case1,2)

##def solution(): return result<<[x,y,b[x,y]]
#bulid_frame 입력
#x,y, a,b 
    # check()==T 

    # delete()==T
#result 출력

In [ ]:
##기둥과 보 설치
import numpy as np
##def check(): return T/F
def check(x,y,a,build):
    #case1.기둥 x y 0 1 >> b[x,y]=0
    if a==0:
        #바닥 위/보의 끝/기둥 위
        if y==0 or build[x-1][y]==1 or build[x][y]==1 or build[x][y-1]==0:
            return True

    #case2.보 x y 1 1 >> b[x,y]=1
    if a==1:
        #기둥 위/양쪽 보
        if build[x][y-1]==0 or build[x+1][y-1]==0 or (build[x-1][y]==1 and build[x+1][y]==1):
            return True

##def delete(): return T/F
def delete(x,y,a,build):
    build[x][y] = -1
#기둥 삭제 #x,y >check([x,y+1]:case1,2 , [x-1,y+1]:case2)
    if check(x,y+1,0,build) and check(x,y+1,1,build) and check(x-1,y+1,1,build):
        return True

#보 삭제 #x,y >check([x-1,y]:case2 , [x,y]:case1, [x+1,y]:case1,2)
    if check(x-1,y,1,build) and check(x,y,0,build) and check(x+1,y,0,build) and check(x+1,y,1,build):
        return True

##def solution(): return result<<[x,y,b[x,y]]
def solution(n, build_frame):
    build = np.array([[-1]*(n+1) for _ in range(n+1)])
    print(build)
    #bulid_frame 입력
    for i in range(len(build_frame)):
        x,y,a,b = build_frame[i]

        # check()==T 
        if b==1:
            if check(x,y,a,build)==True:
                build[x][y]=a
                print("build",x,y,a)
            else:
                print("denied",x,y,a)

        # delete()==T
        if b==0:
            if delete(x,y,a,build)==True:
                # build[x][y]=-1
                print("del",x,y,a)
            else:
                build[x][y]=a
                print("denied",x,y,a)
                
        print(build)

    #result 출력        
    result = [[x,y,build[x][y]] for x in range(n+1) for y in range(n+1) \
              if build[x][y]!=-1]              
    return result

solution(5,[[0, 0, 0, 1], [2, 0, 0, 1], [4, 0, 0, 1], [0, 1, 1, 1], [1, 1, 1, 1], [2, 1, 1, 1], [3, 1, 1, 1], [2, 0, 0, 0], [1, 1, 1, 0], [2, 2, 0, 1]])

[[-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 0 0 0
[[ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 2 0 0
[[ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 4 0 0
[[ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 0 1 1
[[ 0  1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 1 1 1
[[ 0  1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 2 1 1
[[ 0  1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1]
 [ 0  1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1]]
build 3 1 1
[[ 0  1 -1 -1 -1 -1]
 [-1  

[[0, 0, 0], [0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 1, 1], [4, 0, 0]]

In [ ]:
##치킨배달

#지도 생성
#치킨집 최대 13
#치킨집 개수 중 M개 선택
#치킨거리 계산
#최소

In [15]:
##치킨배달
from itertools import combinations
#지도 생성
# n, m = map(int, input().split())
# ch_map = [[0]*n for _ in range(n)]
# for i in range(n):
#     ch_map[i] = list(map(int, input().split()))

n = 5
m = 2
ch_map = [[0, 2, 0, 1, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [2, 0, 0, 1, 1], [2, 2, 0, 1, 2]]


#치킨집 개수 중 M개 선택
ch_num=0
ch_list=[]
for i in range(n):
    for j in range(n):
        if ch_map[i][j]==2:
            ch_num +=1
            ch_list.append([i,j])
print(ch_num,ch_list)

live_ch_list=list(combinations(ch_list,m))
print(len(live_ch_list))

#치킨거리 계산 >>>가장 가까운 치킨집 구현 안함
def get_dist(live_stores, ch_map):
    for k in range(m):
        x, y = live_stores[k][0], live_stores[k][1]
        ch_dist = 0
        for i in range(n):
            for j in range(n):
                if ch_map[i][j]==1:
                    a, b = i, j
                    ch_dist += abs(a-x)+abs(b-y)
    return ch_dist

ch_dist_list=[]
for _ in range(len(live_ch_list)):
    ch_dist = get_dist(live_ch_list[_], ch_map)
    ch_dist_list.append(ch_dist)
print(len(ch_dist_list),ch_dist_list)
#최소
result = min(ch_dist_list)
print(result)

5 [[0, 1], [3, 0], [4, 0], [4, 1], [4, 4]]
10
10 [23, 27, 23, 21, 27, 23, 21, 23, 21, 21]
21


In [ ]:
##외벽 점검
