# Q15. 특정 거리의 도시 찾기: PASS 30/30min

###풀이과정



In [ ]:
#도시 개수, 도로 개수, 최단 거리 정보, 출발도시 번호
n, m, k, x = map(int, input().split())

#도로 연결 >> 인접 리스트 방식
graph = [[] for _ in range(n+1)]

#1-base, 단방향 도로정보 입력
for _ in range(m):
    a, b = map(int, input().split())
    graph[a].append(b)


print(graph)

4 4 2 1
1 2
1 3
2 3
2 4
[[], [2, 3], [3, 4], [], []]


In [ ]:
n, m, k, x = 4, 4, 2, 1
graph = [[], [2, 3], [3, 4], [], []]

In [ ]:
#최단거리>>BFS
from collections import deque

#초기화
visited = [False for _ in range(n+1)]
dist = [0 for _ in range(n+1)]

def bfs(x, k, graph, visited, dist):
    #시작 노드
    q = deque([x])
    visited[x] = True
    dist[x] = 0
    #거리 업데이트
    while q: #모든 노드 탐색할때까지
        v = q.popleft() #큐에서 확인할 노드 v
        for i in graph[v]: #노드 v와 연결된 모든 i
            if not visited[i]: #i가 방문처리 안되어있다면
                q.append(i)#i를 큐에 삽입
                visited[i] = True#i 방문처리
                dist[i] = dist[v]+1
    #최단거리 k인 노드출력
    result = []
    for i in range(1,n+1):
        if dist[i] == k:
            result.append(i)
    if len(result) == 0:
        return -1
    else:
        result.sort()
        return result


In [ ]:
bfs(x, k, graph, visited, dist)

[4]

###해답

In [ ]:
import time
from collections import deque

n, m, k, x = map(int, input().split())
graph = [[] for _ in range(n+1)]
for _ in range(m):
    a, b = map(int, input().split())
    graph[a].append(b)

start = time.time()
#초기화
visited = [False for _ in range(n+1)]
dist = [0 for _ in range(n+1)]

def bfs(x, k, graph, visited, dist):
    #시작 노드
    q = deque([x])
    visited[x] = True
    dist[x] = 0
    #거리 업데이트
    while q: #모든 노드 탐색할때까지
        v = q.popleft() #큐에서 확인할 노드 v
        for i in graph[v]: #노드 v와 연결된 모든 i
            if not visited[i]: #i가 방문처리 안되어있다면
                q.append(i)#i를 큐에 삽입
                visited[i] = True#i 방문처리
                dist[i] = dist[v]+1
    #최단거리 k인 노드출력
    dist_k = []
    for i in range(1,n+1):
        if dist[i] == k:
            dist_k.append(i)
    if len(dist_k) == 0:
        return -1
    else:
        dist_k.sort()
        return dist_k

result = bfs(x, k, graph, visited, dist)
for i in range(len(result)):
    print(result[i])

time.sleep(1)
print(f"{time.time()-start:.4f} sec")

4 4 1 1
1 2
1 3
2 3
2 4
2
3
1.0030 sec


#Q16.연구소:FAIL 60/40min

###풀이과정

In [ ]:
n, m = map(int,input().split())
data = []
for _ in range(n):
    data.append(list(map(int, input().split())))
print(data)

4 6
0 0 0 0 0 0
1 0 0 0 0 2
1 1 1 0 0 2
0 0 0 0 0 2
[[0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 2], [1, 1, 1, 0, 0, 2], [0, 0, 0, 0, 0, 2]]


In [ ]:
#그리디
empty = []
for i in range(n):
    for j in range(m):
        if data[i][j]==0:
            empty.append([i,j])
print(len(empty),empty)

17 [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [1, 1], [1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 0], [3, 1], [3, 2], [3, 3], [3, 4]]


In [ ]:
import itertools
walls = list(itertools.combinations(empty, 3))
print(len(walls), walls[0])

680 ([0, 0], [0, 1], [0, 2])


In [ ]:
#벽설치
def build(data, wall):
    graph = data
    for i in range(3):
        graph[wall[i][0]][wall[i][1]] = 1
    return graph

print(build(data,walls[0]))

[[1, 1, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2], [1, 1, 1, 2, 2, 2], [2, 2, 2, 2, 2, 2]]


In [ ]:
import numpy as np
dx = [-1,0,1,0]
dy = [0,1,0,-1]

#dfs 바이러스 지점 x,y에 대해 수행
def dfs(x,y,graph):
    for i in range(4): #동서남북 중에
        nx = x + dx[i]
        ny = y + dy[i]
        if nx>=0 and nx<n and ny>=0 and ny<m: #범위내 nx,ny에서
            if graph[nx][ny] == 0:#빈공간이면
                graph[nx][ny] = 2 #바이러스 퍼짐
                dfs(nx,ny,graph) #재귀함수 수행

#바이러스 퍼뜨리기
# graph = build(data,walls[0])
# for x in range(n):
#     for y in range(m):
#         if graph[x][y]==2:
#             dfs(x,y,graph)

# print(np.array(graph))


In [ ]:
#컴비네이션 및 출력
def virus(build):
    for x in range(n):
        for y in range(m):
            if build[x][y]==2:
                dfs(x,y,build)
    return build

def safe(build):
    count = 0
    for x in range(n):
        for y in range(m):
            if build[x][y]==0:
                count +=1
    return count

data=[[0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 2], [1, 1, 1, 0, 0, 2], [0, 0, 0, 0, 0, 2]]
count_list=[]
for c in range(3):
    print('0\n',np.array(data))
    c_wall = walls[c]
    c_build = build(data, c_wall)
    print('1\n',np.array(c_build))
    v_graph = virus(c_build)
    print('2\n',np.array(v_graph))
    s_count = safe(v_graph)
    print('3\n',s_count)
    count_list.append(s_count)

print(max(count_list))


0
 [[0 0 0 0 0 0]
 [1 0 0 0 0 2]
 [1 1 1 0 0 2]
 [0 0 0 0 0 2]]
1
 [[1 1 1 0 0 0]
 [1 0 0 0 0 2]
 [1 1 1 0 0 2]
 [0 0 0 0 0 2]]
2
 [[1 1 1 2 2 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
3
 0
0
 [[1 1 1 2 2 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
1
 [[1 1 1 1 2 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
2
 [[1 1 1 1 2 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
3
 0
0
 [[1 1 1 1 2 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
1
 [[1 1 1 1 1 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
2
 [[1 1 1 1 1 2]
 [1 2 2 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 2 2 2]]
3
 0
0


#Q17. 경쟁적 전염: PASS 50/50min

###풀이과정

In [ ]:
import numpy as np
n, k = 3, 3
data = [[1,0,2],[0,0,0],[3,0,0]]
s, x, y = 2, 3, 2
print(np.array(data))

[[1 0 2]
 [0 0 0]
 [3 0 0]]


In [ ]:
#바이러스 순서대로 큐 생성
from collections import deque

virus = []
for i in range(n):
    for j in range(k):
        if data[i][j]!=0:
            virus.append([data[i][j],i,j,0])
virus.sort()
print(virus)

dx = [-1,0,1,0]
dy = [0,1,0,-1]

#큐 순서대로 바이러스 업데이트
q = deque(virus)
while q:
    v_num, v_x, v_y, v_s = q.popleft()
    print('pop',q)
    if v_s<s:
        for i in range(4):
            nx = v_x + dx[i]
            ny = v_y + dy[i]
            if nx>=0 and nx<n and ny>=0 and ny<k:
                if data[nx][ny]==0:
                    data[nx][ny]=v_num
                    q.append([v_num, nx, ny, v_s+1])
                    print('append',q)

print(np.array(data))

[[1, 0, 0, 0], [2, 0, 2, 0], [3, 2, 0, 0]]
pop deque([[2, 0, 2, 0], [3, 2, 0, 0]])
append deque([[2, 0, 2, 0], [3, 2, 0, 0], [1, 0, 1, 1]])
append deque([[2, 0, 2, 0], [3, 2, 0, 0], [1, 0, 1, 1], [1, 1, 0, 1]])
pop deque([[3, 2, 0, 0], [1, 0, 1, 1], [1, 1, 0, 1]])
append deque([[3, 2, 0, 0], [1, 0, 1, 1], [1, 1, 0, 1], [2, 1, 2, 1]])
pop deque([[1, 0, 1, 1], [1, 1, 0, 1], [2, 1, 2, 1]])
append deque([[1, 0, 1, 1], [1, 1, 0, 1], [2, 1, 2, 1], [3, 2, 1, 1]])
pop deque([[1, 1, 0, 1], [2, 1, 2, 1], [3, 2, 1, 1]])
append deque([[1, 1, 0, 1], [2, 1, 2, 1], [3, 2, 1, 1], [1, 1, 1, 2]])
pop deque([[2, 1, 2, 1], [3, 2, 1, 1], [1, 1, 1, 2]])
pop deque([[3, 2, 1, 1], [1, 1, 1, 2]])
append deque([[3, 2, 1, 1], [1, 1, 1, 2], [2, 2, 2, 2]])
pop deque([[1, 1, 1, 2], [2, 2, 2, 2]])
pop deque([[2, 2, 2, 2]])
pop deque([])
[[1 1 2]
 [1 1 2]
 [3 3 2]]


#Q18.괄호변환

###풀이과정 : FAIL 20/20min **올바른 문자열 판단방법 생각못함

#Q19.연산자 끼워 넣기: FAIL 40/30min

###풀이과정

In [9]:
n = int(input())

data = list(map(int, input().split()))
add,sub,mul,div = map(int, input().split())

min_value = 1e9
max_value = -1e9

def dfs(i, now):
    global min_value, max_value, add, sub, mul, div
    print('dfs',i,now)
    if i==n:
        min_value = min(min_value, now)
        max_value = max(max_value, now)
        print('i==n', min_value, max_value)
    else:
        if add > 0:
            add -= 1
            print(add,'a1')
            dfs(i+1, now+data[i])
            print(add,'a2')
            add+=1

        if sub > 0:
            sub -= 1
            dfs(i+1, now-data[i])
            # sub+=1

        if mul > 0:
            mul -= 1
            print(mul,'m1')
            dfs(i+1, now*data[i])
            print(mul,'m2')
            mul+=1

        if div > 0:
            div -= 1
            dfs(i+1, int(now/data[i]))
            # div += 1

dfs(1,data[0])
print(max_value,min_value)

3
3 4 5
1 0 1 0
dfs 1 3
0 a1
dfs 2 7
0 m1
dfs 3 35
i==n 35 35
0 m2
0 a2
0 m1
dfs 2 12
0 a1
dfs 3 17
i==n 17 35
0 a2
0 m2
35 17


#20. 감시 피하기:FAIL 80/60min 디버깅하면 될거 같기도...

In [11]:
n = int(input())
data = []
for _ in range(n):
    data.append(list(input().split()))
print(data)

5
X S X X T
T X S X X
X X X X X
X T X X X 
X X T X X
[['X', 'S', 'X', 'X', 'T'], ['T', 'X', 'S', 'X', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'T', 'X', 'X', 'X'], ['X', 'X', 'T', 'X', 'X']]


In [13]:
import numpy as np
print(np.array(data))

[['X' 'S' 'X' 'X' 'T']
 ['T' 'X' 'S' 'X' 'X']
 ['X' 'X' 'X' 'X' 'X']
 ['X' 'T' 'X' 'X' 'X']
 ['X' 'X' 'T' 'X' 'X']]


In [28]:
#장애물 설치 경우의수 탐색
def dfs(count, data):
    if count == 3:  # 장애물 3개 설치할때
        # 감시 피할수있는지
        if safe(data):
            return True
        return False

    for i in range(n):
        for j in range(n):
            if data[i][j] == 'X':  # 빈칸에 장애물 설치
                data[i][j] = 'O'

                # 다음 장애물 설치
                if dfs(count + 1, data):# T>>종료
                    return True

                data[i][j] = 'X'  # F>>다시 빈칸으로

    return False

In [21]:
def safe(data):
    dx = [-1,0,1,0]
    dy = [0,1,0,-1]

    for x in range(n):
        for y in range(n):
            if data[x][y]=='T': #선생님마다 체크
                for i in range(4):

                    nx = x + dx[i]
                    ny = y + dy[i]

                    while nx>=0 and nx<n and ny>=0 and ny<n:
                        if data[nx][ny]=='S': #학생 만나면 F
                            return False
                        elif data[nx][ny]=='0': #장애물 break
                            break
                        nx += dx[i]#한방향으로 이동
                        ny += dy[i]
    return True #통과

In [30]:
n = 5
data = [['X', 'S', 'X', 'X', 'T'], ['T', 'X', 'S', 'X', 'X'], ['X', 'X', 'X', 'X', 'X'], ['X', 'T', 'X', 'X', 'X'], ['X', 'X', 'T', 'X', 'X']]
# data = [['S', 'S', 'S', 'T'], ['X', 'X', 'X', 'X'], ['X', 'X', 'X', 'X'], ['T', 'T', 'T', 'X']]
dfs(0,data)

False