In [25]:
import time
start = time.time()
'''
실전 Q2. 1로 만들기 PASS 20/20MIN

26 > 25 > 5 > 1
1 : 1
2 : 1
3 : 1
4 : f(2)+1=2
5 : 1
6 : min(f(2)+1, f(3)+1)
'''
def div(n,x):
    return n//x

def sub(n):
    return n-1

c = [30000]*30000
c[0]=0
c[1]=0
c[2]=1
c[3]=1
c[5]=1

def f(n):
    #종료조건
    if n==1 or n==2 or n==3 or n==5:
        return 1
    #메모이제이션
    if c[n] !=30000:
        return c[n]

    if n%5==0:
        c[n]=min(c[n],f(div(n,5))+1)
        # print(c)
    if n%3==0:
        c[n]=min(c[n],f(div(n,3))+1)
        #print(c)
    if n%2==0:
        c[n]=min(c[n],f(div(n,2))+1)
        # print(c)
    c[n]=min(c[n],f(sub(n))+1)

    return c[n]

n=500
# f[10]
# print(c)
print(f(n))

end =time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

5
0.0060 s


In [45]:
start=time.time()
'''
실전 Q3.개미 전사 PASS 20/30MIN

f(1)<f(3)<f(5)< ...
f(2)<f(4)< ...
f(6) : max(f(4)+c[6],f(5))
'''
import random
# n=10
n=4
food = [0]*(n+1)

# c = [random.randint(1, 10) for _ in range(n)]
c = [0,1,3,1,5]
print('창고',c)

food[1] = c[1]
food[2] = max(c[1],c[2])

def f(n):
    #종료
    if n==1:
        return food[1]
    if n==2:
        return food[2]
    if food[n] !=0:
        return food[n]

    food[n] = max(f(n-2)+c[n],f(n-1))
    return food[n]


print(f(n))
print(food)


end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

창고 [0, 1, 3, 1, 5]
8
[0, 1, 3, 3, 8]
0.0095 s


In [53]:
start=time.time()
'''
실전 Q4.바닥 공사 PASS 10/20MIN

f(n) = f(n-1) + 2*f(n-2)
'''

n=10
c = [0]*(n+1)
c[1]=1
c[2]=3
# c[3]=3+2

def f(x):
    #종료
    if x==1 or x==2 or c[x]!=0:
        return c[x]

    c[x] = f(x-1) + 2*f(x-2)
    return c[x]

print(f(5))
print(c)

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

21
[0, 1, 3, 5, 11, 21, 0, 0, 0, 0, 0]
0.0027 s


In [92]:
start=time.time()
'''
실전 Q5.효율적인 화폐 구성 PASS 35/30MIN

bottom-up
'''
N=3
M=15
a = [4, 5, 11]
len_c = max(max(a)+1,M+1)
c = [10001]*(len_c)

for coin in a:
    c[coin] = 1

for i in range(1,M+1):
    if c[i]!=10001:
        for coin in a:
            x = i
            # print('i',x)
            x += coin
            if x > M:
                pass
            else:
                c[x] = min(c[x],c[i]+1)
                print(i,'+',coin,'=', x, c[x])

print(c)
if c[M] == 10001:
    print(-1)
else:
    print(c[M])

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

4 + 4 = 8 2
4 + 5 = 9 2
4 + 11 = 15 2
5 + 4 = 9 2
5 + 5 = 10 2
8 + 4 = 12 3
8 + 5 = 13 3
9 + 4 = 13 3
9 + 5 = 14 3
10 + 4 = 14 3
10 + 5 = 15 2
11 + 4 = 15 2
[10001, 10001, 10001, 10001, 1, 1, 10001, 10001, 2, 2, 2, 1, 3, 3, 3, 2]
2
0.0237 s


In [111]:
start=time.time()
'''
기출 Q31.금광 : PASS 30/30MIN
bottom up

max(down, right, up)
'''
import numpy as np
n=4
m=4
# data = np.array([1, 3, 3, 2, 2 ,1, 4, 1, 0, 6, 4, 7])
data = np.array([1,3,1,5,2,2,4,1,5,0,2,3,0,6,1,2])
data = data.reshape(n,m)
print(data)

c = [[0]*m]*n
c = np.array(c)
for i in range(n):
    c[i][0] = data[i][0]
print(c)

for j in range(1,m):
    for i in range(n):
        if i==0:
            r = c[i][j-1]
            u = c[i+1][j-1]
            c[i][j] = max(r,u)+data[i][j]
        elif i==n-1:
            d = c[i-1][j-1]
            r = c[i][j-1]
            c[i][j] = max(d,r)+data[i][j]
        else:
            d = c[i-1][j-1]
            r = c[i][j-1]
            u = c[i+1][j-1]
            c[i][j] = max(d,r,u)+data[i][j]
    print(c)

print(max(c[:,m-1]))

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

[[1 3 1 5]
 [2 2 4 1]
 [5 0 2 3]
 [0 6 1 2]]
[[1 0 0 0]
 [2 0 0 0]
 [5 0 0 0]
 [0 0 0 0]]
[[ 1  5  0  0]
 [ 2  7  0  0]
 [ 5  5  0  0]
 [ 0 11  0  0]]
[[ 1  5  8  0]
 [ 2  7 11  0]
 [ 5  5 13  0]
 [ 0 11 12  0]]
[[ 1  5  8 16]
 [ 2  7 11 14]
 [ 5  5 13 16]
 [ 0 11 12 15]]
16
0.0100 s


In [153]:
start=time.time()
'''
기출 Q32.정수 삼각형 : PASS 15/30MIN
bottom up


'''
import numpy as np
n=5
data = [[7],[3,8],[8,1,0],[2,7,4,4],[4,5,2,6,5]]

c = [[0]*n]*n
c = np.array(c)
print(c)

c[0][0]=data[0][0]
for i in range(1,n):
    for j in range(i+1):
        if j==0:
            c[i][j]=data[i][j]+c[i-1][j]
        elif j==i:
            c[i][j]=data[i][j]+c[i-1][j-1]
        else:
            c[i][j]=data[i][j]+max(c[i-1][j-1],c[i-1][j])
print(c)
print(max(c[n-1,:]))

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 7  0  0  0  0]
 [10 15  0  0  0]
 [18 16 15  0  0]
 [20 25 20 19  0]
 [24 30 27 26 24]]
30
0.0038 s


In [165]:
start=time.time()
'''
기출 Q33.퇴사 : FAIL 30/30min
bottom up
'''
import numpy as np
n=7
data = [[0,0],[3,10],[5,20],[1,10],[1,20],[2,15],[4,40],[2,200]]
c = [0]*(n+1) #날짜별 받은 돈
print(c)

#날짜별로 반복
#다음 날짜별로 돈 계산후 비교(n일까지)
for i in range(1,n+1): # 시작 날짜
    pay = 0
    day = i
    print(i)
    while True: # n까지 계속 계산
        if day > n: # day가 n 초과시 종료
            break
        else:
            c[day] =data[i][1] # 받은 돈
            day +=data[i][0] # 다음 날짜
            print(c)
    pay = max(pay,sum(c)) # 날짜별 받은 돈 합산
    print(pay,sum(c))

print(pay)


end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

[0, 0, 0, 0, 0, 0, 0, 0]
1
[0, 10, 0, 0, 0, 0, 0, 0]
[0, 10, 0, 0, 10, 0, 0, 0]
[0, 10, 0, 0, 10, 0, 0, 10]
30 30
2
[0, 10, 20, 0, 10, 0, 0, 10]
[0, 10, 20, 0, 10, 0, 0, 20]
60 60
3
[0, 10, 20, 10, 10, 0, 0, 20]
[0, 10, 20, 10, 10, 0, 0, 20]
[0, 10, 20, 10, 10, 10, 0, 20]
[0, 10, 20, 10, 10, 10, 10, 20]
[0, 10, 20, 10, 10, 10, 10, 10]
80 80
4
[0, 10, 20, 10, 20, 10, 10, 10]
[0, 10, 20, 10, 20, 20, 10, 10]
[0, 10, 20, 10, 20, 20, 20, 10]
[0, 10, 20, 10, 20, 20, 20, 20]
120 120
5
[0, 10, 20, 10, 20, 15, 20, 20]
[0, 10, 20, 10, 20, 15, 20, 15]
110 110
6
[0, 10, 20, 10, 20, 15, 40, 15]
130 130
7
[0, 10, 20, 10, 20, 15, 40, 200]
315 315
315
0.0204 s


In [213]:
start=time.time()
'''
기출 Q34.병사 배치하기 : FAIL 40/40min
bottom up

'''
import numpy as np
n=7
c = [0,15,11,4,8,5,2,4]

max_ans = 0
def check(a, b, ans):
    if a==n:
        print(ans)
        # check(a,b+1,ans=1)
        return ans

    if b<n+1:
        if c[a] > c[b]:##뒤에 병사가 전투력 낮을때
            # print('i',a,b,ans)
            return check(b,b+1,ans+1)

        else:#뒤에 병사가 전투력 높을때
            # print('e',a,b,ans)
            b+=1
            return check(a,b,ans)
    else:
        return check(a+1,a+2,ans)



for i in range(1,n): #시작점
    for j in range(i+1, n+1):
        ans = 1
        return_ans = check(i,j,ans)
        max_ans = max(max_ans,return_ans)

print(n-max_ans)

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

4
3
4
3
2
2
3
4
3
2
2
2
2
2
3
3
2
2
2
2
1
3
0.0079 s


In [212]:
start=time.time()
'''
기출 Q35.못생긴 수: PASS 20/30min

'''
n = 10
#못생긴수 리스트
c = [1,2,3,5]
#리스트 길이 n까지


def f(c):
    #리스트 요소에 차례대로 2,3,5 곱하기
    for x in c:
        p2 = x*2
        p3 = x*3
        p5 = x*5
        #리스트 길이 n 종료
        if len(c) < n+1:
            #리스트에 요소 중복이 없으면 추가
            if p2 not in c:
                c.append(p2)
                #리스트 정렬
                c.sort()
                print(c)
                return f(c)
            if p3 not in c:
                c.append(p3)
                c.sort()
                print(c)
                return f(c)
            if p5 not in c:
                c.append(p5)
                c.sort()
                print(c)
                return f(c)
        else:
            return c[n-1]

result = f(c)
print(result)

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 10]
[1, 2, 3, 4, 5, 6, 9, 10]
[1, 2, 3, 4, 5, 6, 9, 10, 15]
[1, 2, 3, 4, 5, 6, 8, 9, 10, 15]
[1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15]
12
0.0105 s


In [220]:
start=time.time()
'''
기출 Q36.편집거리: FAIL 30/30min

1.같은 알파벳 리스트에 저장
2.빈 리스트 개수 세기(insert & replace)
3.del
'''
a = 'sunday'
b = 'saturday'
c = [0]*len(b)
k=0
for i in range(len(a)):
    for j in range(k,len(b)):
        if a[i]== b[j]:
            c[j] = a[i]
            k=i+1
print(c)
ans=0
for z in c:
    if z==0:
        ans+=1
print(ans)

end=time.time()
exe_time = end-start
print(f'{exe_time:.4f}','s')

['s', 0, 0, 'u', 0, 'd', 'a', 'y']
3
0.0033 s
